### PR TITLE
Add option to change build Success message

### PR DESCRIPTION
**Pull request by bokswagen**

### CODE REVIEW

**Comment by Turbo87** [comment]
@bokswagen may I ask why you want to modify the message?

**Comment by bokswagen** [comment]
When you have multiple webpack configs running, it's good to know which ones changed

**Comment by Turbo87** [comment]
wouldn't it be better in that case to prefix it with the project name automatically instead of manually having to set the message? with the proposed solution you still don't know which project the notification is coming from if the build fails

**Comment by Gvozd** [comment]
I find the `title` to be a suitable (and sufficient) place to set the project name

Also, this PR looks incomplete, because you can customize the message only for a successful build, but not for warnings/errors
But if you change them, then the configuration will unnecessarily increase.
It may be worth changing the message with a function, by analogy with [dynamic headers](#53), but I'm not sure yet about this need

For this reason, I am closing this OL

**Pull request closed without merging**
