### PR TITLE
Prefix error + warning messages

### PR DESCRIPTION
**Pull request by martijnrusschen**
Since your file names are pretty long normally, the only thing I can see in the notifications are the filenames. I'd prefer to have the notification start with `Error:` or `Warning:` instead.

### CODE REVIEW

**Comment by Turbo87** [comment]
could you add a quick screenshot of how the notification changes due to this?

**Comment by martijnrusschen** [comment]
This is an example of an error: 
screen shot 2016-02-22 at 13 40 49

**Comment by Turbo87** [comment]
ah cool, thanks!

**Comment by martijnrusschen** [comment]
Cool, are you planning a new release soon?

**Comment by Turbo87** [comment]
@martijnrusschen just published v1.3.0. should be available on NPM in a few minutes.

**Comment by martijnrusschen** [comment]
Awesome!

**Comment by Turbo87** [comment]
might be a few more minutes. looks like the TravisCI deploy thing didn't work as it should (https://travis-ci.org/Turbo87/webpack-notifier/builds/110943200)

**Pull request merged**
